### ISSUE TITLE
Test runner UI cannot accurately describe the state of assertion verdicts

### ISSUE THREAD

**Issue by jugglinmike** [w3c/aria-at-app#1045]
Currently, the "Test Plan Run" page presents Testers uses a two-state checkbox to convey the state of each assertion verdict, e.g.

> Which statements are true about the response to f (browse mode on)?
>
> - [ ] Role 'group' is conveyed

The value of the assertion verdict is actually indeterminate in two cases, making a two-state checkbox insufficient:

1. When human Testers begin manually running a test and have not yet reported whether or not the assertions are satisfied.
2. When a "bot" tester has collected AT responses for the Test Plan Run and a Test Admin has re-assigned the Test Plan Run to a human Tester

In effect, the "unchecked" state ambiguously describes two different states: "this assertion is not satisfied," and "this assertion has not yet been evaluated."

To date, this ambiguity has been tolerable because the human Tester is the sole arbiter of assertion verdicts. They tacitly track their own progress through the Test Plan Run.

However, the ambiguity will become more confusing as the system gains the ability to automatically re-use verdicts when it recognizes historic test results. In those cases, a human Tester who receives a Test Plan Run from a Bot will not be able to recognize which assertions have been recognized as "failed" and which have not been automatically judged by the system.

**Comment by jugglinmike** [comment]
[The community group discussed this issue briefly during today's meeting.](https://www.w3.org/2024/04/24-aria-at-minutes.html#t04)

**Comment by mcking65** [comment]
Propose that we use Yes/No radios just like we have for undesirable behaviors. Then all the questions have exactly the same format. If neither radio is checked, the verdict is not assigned.

**Comment by jugglinmike** [comment]
Thanks, @mcking65!
