### ISSUE TITLE
New test run contributor?

### ISSUE THREAD

**Issue by cookiecrook** [w3c/aria-at-app#1066]
> You are not yet registered to participate! Let us know you want to help by [opening an issue on GitHub](https://github.com/w3c/aria-at-app/issues/new).

There was no template, so I'm not really sure what you want in this issue tracker. Let me know if there's more to do.

**Comment by cookiecrook** [comment]
Or if you're requesting a reference to an issue in the main repo, here's a recent one:
- https://github.com/w3c/aria-at/issues/1057

**Comment by jscholes** [comment]
@cookiecrook Are you (or someone else) trying to run a test plan to provide results?  Or review a test plan as a vendor representative.

**Comment by cookiecrook** [comment]
Both

**Comment by cookiecrook** [comment]
Both. I plan to do a full pass review and run of the [AT Reports](https://aria-at.w3.org/reports) VO/Mac column after WWDC week, so mid-June.

**Comment by cookiecrook** [comment]
Bueller?

**Comment by jscholes** [comment]
@cookiecrook You have now been added as an Apple vendor representative, allowing you to use the Candidate Review functionality.  This facilitates direct access to test plans, tests, the test case examples, and all adjacent data.

https://aria-at.w3.org/candidate-review

Please let us know if this access doesn't provide what you need.
