### ISSUE TITLE
Error when signed up for Modal Dialog with Jaws/Chrome.

### ISSUE THREAD

**Issue by ccanash** [w3c/aria-at-app#1090]
Issue reported by @hadirangin: 

They  signed up for Modal Dialog with Jaws/Chrome and when  accessing the Modal Dialog test plan they get the following error:
Int cannot represent non-integer value: 14.1 Int cannot represent non-integer value: 16.1 Int cannot represent non-integer value: 40.1

**Comment by howard-e** [comment]
Closing as duplicate of #1085
