### ISSUE TITLE
Incorrect VoiceOver Bot Results for Color Viewer Slider Test Plan

### ISSUE THREAD

**Issue by IsaDC** [w3c/aria-at-app#1136]
The results recorded by the VoiceOver bot are not valid, except for Test 8: Decrement a slider to the minimum value. I haven't been able to reproduce the bot's results manually, but there is a fresh run in the Sandbox for you to take a look.

#### Example of My Results Compared to the Bot's:
**Test 1: Navigate forwards to a slider**

**After 'Control+Option+Right Arrow then Control+Option+Right Arrow':**

- **VoiceOver Bot:**
  - Color (RGB): 128, 128, 128 
  - Color (RGB): 128, 128, 128 
  - Color (RGB): text You are currently on a selectable text.

- **Isa:**
  - Red You are currently on a selectable text.
  - 128 Red slider You are currently on a slider. To start interacting with the slider, press Control-Option-Shift-Down Arrow.

**Comment by IsaDC** [comment]
CC @mcking65  @jugglinmike

**Comment by jugglinmike** [comment]
By the way, here's the command I used to run the tests:

    node aria-at-automation-harness/bin/host.js run-plan \
      --plan-workingdir aria-at/build/tests/horizontal-slider \
      '{reference/**,test-*-voiceover_macos.*}' \
      --agent-web-driver-url=http://127.0.0.1:4444 \
      --agent-at-driver-url=ws://127.0.0.1:4382/session \
      --reference-hostname=127.0.0.1 \
      --agent-web-driver-browser=safari

**Comment by outofambit** [comment]
Hi @IsaDC! I was able to reproduce this on macOS 14 and have a potential fix in the works at https://github.com/bocoup/aria-at-gh-actions-helper/pull/24. Will followup here when its ready and live.

**Comment by IsaDC** [comment]
Thank you @outofambit

**Comment by outofambit** [comment]
Hi again @IsaDC! These changes are now live. Could you take a look at [it on staging](https://aria-at-staging.w3.org/test-queue#horizontal-slider) and let me know?

**Comment by IsaDC** [comment]
Thank you, @outofambit , the results look much better. However, when pressing shift+tab, focus moves to the "Green             slider".

**Comment by ccanash** [comment]
Thank you for testing @IsaDC  and reporting the new issue. I have created a follow up #1159  to track the new issue.
