### ISSUE TITLE
Cannot connect to API on linux

### ISSUE THREAD

**Issue by spectranaut** [w3c/aria-at-app#14]
When I run:

1. `yarn dev` at the top level
2. `curl --location --request POST 'localhost:5000/api/user' --header 'Content-Type: application/json' --data-raw '{"fullname": "Foo Bar", "username": "foobar", "email": "foo@bar.com" }'`

The curl does not return and I see the following error in the server:
```
api_1  | Error: SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:5432
```

If I run `npm dev` from the server directory it works.

**Comment by s3ththompson** [comment]
Closing as obsolete. Please reopen if this is still an issue.
