### ISSUE TITLE
Test Management page doesn't show new Test Cycle after initiating

### ISSUE THREAD

**Issue by zcorpan** [w3c/aria-at-app#187]
Steps to reproduce:

1. Initiate a new test cycle. After clicking the "Initiate Cycle" button you get to the Test Management page, showing existing test cycles.

Expected results:

The new test cycle should show in the table.

Actual results:

The new test cycle is missing in the table. After a page reload it shows up.

**Comment by richnoah** [comment]
@zcorpan is the bug you mention still occurring?

**Comment by zcorpan** [comment]
I think Test Cycle isn't a thing anymore. Closing.
