### ISSUE TITLE
When running app locally, the Test Queue page crashes

### ISSUE THREAD

**Issue by alflennik** [w3c/aria-at-app#272]
<img width="994" alt="Screenshot of browser dev tools showing uncaught Typerror cannot read property slice of undefined, occurring in the current git commit React component" src="https://user-images.githubusercontent.com/5255858/111199226-c9abcc00-8596-11eb-8a0d-da60372e4926.png">

Reproduction steps:
- Clear your Postgres database
- Follow the installation steps
- Log in for the first time
- Navigate to the Test Queue page

I was able to fix this error by changing the settings on the Test Configuration page.

Expected behavior:
- Should not crash. 
- I would expect a message on the test queue page saying something like, "To view your test queue please configure the tests on the test configuration page"

**Comment by sinabahram** [comment]
Quick note: would it please be possible to always, without exception, provide alt text on any images? Thanks so much.

**Comment by alflennik** [comment]
Thanks @sinabahram for that. Now fixed.

**Comment by richnoah** [comment]
@alflennik is this still an issue that needs to remain open or can it be closed?

**Comment by alflennik** [comment]
This is fixed! It can be closed. Thanks Rich.
