### ISSUE TITLE
Update Homepage copy

### ISSUE THREAD

**Issue by richnoah** [w3c/aria-at-app#330]
The objective of this issue is to update the existing copy of the homepage, https://aria-at.w3.org/.  The final text will be a collaboration between @s3ththompson and @mcking65 .

**Comment by boazsender** [comment]
Here are my proposed credits. I think they should go in the footer of the site: 

> Accessible Rich Internet Applications and Assistive Technologies ARIA AT (also known as) is a project conceived by Matt King. Criteria definition and test authoring is lead by Sina Bahram, Isabel Del Castillo, and James Scholes from Prime Access Consulting (PAC). Test running, results reporting, and automation software are designed and implemented by Jes Daigle, Sheila Moussavi, Howard Edwards, Z Goddard, Simon Pieters, Isaac Durazo, Mike Pennisi, Seth Thompson, Rich Noah, and Boaz Sender from Bocoup. Thank you to all the participants from the W3C ARIA AT Community Group. which is chaired by Michael Fairchild from Deque Systems, and Matt King from Facebook Accessibility, with special input from JaEun Jemma Ku and Jon Gundersoon from University of Illinois at Urbana-Champaign.
 
Who else are we missing?
