### ISSUE TITLE
Test Plan Updater

### ISSUE THREAD

**Issue by richnoah** [w3c/aria-at-app#407]
As a Test Plan Administrator, I need the ability to update the version of a test plan being used, and when I make an update any previous results can be copied over.

The feature can be seen by those with administrator access.

This current feature will copy over prior test results to a new version of a test plan as long as the new test plan matches the prior version.

Test Plan Administrators will also have the ability to delete the prior test plan once the results are copied over.

https://aria-at-app-sandbox.bocoup.com/

@jscholes @SamuelHShaw

**Comment by jscholes** [comment]
@richnoah / @s3ththompson, this is looking good to me!  I tested both cases of result copying, i.e. all results can be carried over, versus some results cannot be, and the messaging is all pretty clear.

The only minor change I'd suggest is to the label of the checkbox.  Right now, it reads: "Back up test plan before update".  I think it would be slightly more unambiguous as something like, "Retain older versions of test plan and results".  That wording itself may need massaging, but my primary aim is to make sure the aspect of versioning is captured in the label.  It could even just be, "Back up previous plan version before update".  What do you think?

I have no other pressing changes to suggest that should block a deploy.  Great stuff 👍

**Comment by richnoah** [comment]
@jscholes @mcking65 this feature was deployed to production with the above feedback.  This deployment was communicated via email on Wednesday, March 30th to the public-aria-at@w3.org email group.

At this point, I will be closing this issue and updating the project board.  Please feel free to open a new issue should any items need to be addressed.
