### ISSUE TITLE
Update testing instructions to reflect presence of setup button

### ISSUE THREAD

**Issue by jscholes** [w3c/aria-at-app#443]
Currently, step 2 of the instructions presented to testers by the app reads:

> Activate the "Open test page" button below, which opens the example to test in a new window and runs a script that ... `<setup script purpose>`.

For instance:

> Activate the "Open test page" button below, which opens the example to test in a new window and runs a script that sets focus on a link before the grid.

This information hasn't been accurate since around October of 2021, when a button was added to test case pages allowing the setup script to be manually executed.  As such, I suggest something like the following wording instead:

> `2.` Activate the "Open test page" button, which opens the example to test in a new window and sets focus on the "Run Test Setup" button.
> 
> `3.` Press the "Run Test Setup" button, which runs a script that `<setup script description>`, allowing testing commands to be executed from that point.  You should press this button again whenever you reopen or refresh the example.

**Comment by jscholes** [comment]
CC @richnoah / @s3ththompson

**Comment by mcking65** [comment]
This is covered by w3c/aria-at#977. Currently the details are in w3c/aria-at#978, but they will be integrated into the 977 spec.
