### ISSUE TITLE
Candidate Test Plans page row consolidation: Activating "Mark as Candidate" incorrectly changes candidate phase start date

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-at-app#522]
May be related to #500 

From testing in sandbox:
https://aria-at-app-sandbox.bocoup.com/test-queue

To reproduce this bug:
1. A test plan is in the state where:
    1. It is present in both test queue and in candidate tests
    1. In the test queue it has report status In Review with button "Mark as Candidate"
    1. On the candidate tests page, the available data for the plan is for a version of the test plan that is older than the version of the plan that is in the test queue.
1. In the test queue, activate the "Mark as Candidate" button.
2. 
Actual behavior:
The dates associated with start and end of candidate phase are changed on the candidate test page.
Note the dates on the alert test plan on the candidate test page.

Expected behavior:
Dates are not changed. Updating the test results for a plan that is already in candidate phase should not change anything about the candidate phase status.

We likely need an immediate tactical fix to this issue.

As we look just past the immediate need of publishing updated data for the support table roll out, it is important to understand that there is a fundamental design problem underneath the bug.

The "Mark as Candidate button is performing two separate tasks on two different entities. While one task depends on the other, these tasks should be separated.
* Task 1: Update the version of the test plan that is in candidate review.
* Task 2: Mark results of running a specific version of the test plan for a specific screen reader/browser as "complete" so the test run results are made visible in the reports for that version of the test plan. 

If a given test plan is in candidate phase and we need to update the test plan due to feedback received during the candidate phase, updating the test plan does not change when that plan started the candidate phase of the working mode. It should also not have any effect on the target date for completing the candidate phase. It is expected that test plans will change during the candidate phase in order to incorporate stakeholder feedback.

Also note that the candidate phase start and end are not properties of a screen reader/browser combination. The start and end dates of a phase of the working mode are properties of the test plan itself. A version of a plan includes a set of in-scope or covered assistive technologies, but the plan moves through the working mode for all covered AT, not for one at a time.

**Comment by ccanash** [comment]
This has been triaged and assign to @howard-e for work.
