### ISSUE TITLE
Change port number of Development OAuth app from 5000 to 8000

### ISSUE THREAD

**Issue by evmiguel** [w3c/aria-at-app#566]
Hi @michael-n-cooper,

We recently changed our development port from 5000 to 8000 because macOS has taken over port 5000 for their own purposes. The Development OAuth application would need to reflect that change for our environment to work properly. Could you please run the following steps from the W3C Organization in GitHub:

1. Go to: Settings > Developer Settings > Oauth Apps > ARIA-AT App (Development)
2. In the **Authorization callback URL** box,  http://localhost:5000/api/auth/authorize?service=github to http://localhost:8000/api/auth/authorize?service=github

Many thanks!

**Comment by evmiguel** [comment]
Hi @daniel-montalvo! I saw that you are the point of contact for the ARIA-AT project now. Would you be able to help out with this request?

**Comment by daniel-montalvo** [comment]
@evmiguel 

Sorry for being late with this.

I changed  ARIA-AT Report API (Development) I could not find ARIA-AT App (Development)

Should be done now. Let me know otherwise.

**Comment by daniel-montalvo** [comment]
Hi @evmiguel 
I am assuming this is working now. Closing, feel free to reopen if is still not.
