### ISSUE TITLE
Add Test Plans to the Test Queue: Plan version dropdown shows commits that do not include a change in the chosen test plan

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-at-app#579]
Using the [sandbox on March 25, 2023](https://aria-at-app-sandbox.bocoup.com/test-queue).

When adding a plan to the test queue, the system is surfacing commits that do not include changes to the selected plan.
This enables generation of significant downstream data integrity problems.

Test plans are versioned by their last date of change as derived from the aria-at commit history.
The test plan version is critical information when running a plan through the working mode.
For example, it is esential to know what version of a plan was run to generate a specific result set and when the plan was last changed.

To reproduce the problem:
1. Open the add test plan experience
2. Choose alert
3. Note the list of versions includes every commit to the main branch in w3c/aria-at.
4. Look at the file tree for aria-at.
    As of March 25, 2023, The last commit that change the
    [Alert Test Plan Files](https://github.com/w3c/aria-at/tree/master/tests/alert)
    was [0928bcf on December 8, 2022](https://github.com/w3c/aria-at/commit/0928bcf530efcf4faa677285439701537674e014).

Actual behavior: Commits that do not include changes to the alert plan are listed in the version dropdown.

Expected behavior: Only commits to main with changes to the alert plan are listed.

Because of this problem, I was able to add multiple versions of the alert test plan to the test queue for VoiceOver with Chrome. The VoiceOver/Chrome table shows two rows for alert, one with a March 20 version and another with a March 8 version. This is a serious problem, because it indicates the plan has changed since December 8, but it has not changed. The ramifications of signaling change when in fact there was no change poses major risk to our ability to execute the working mode.

**Comment by ccanash** [comment]
This has been triaged and assigned to @alflennik

**Comment by mcking65** [comment]
Looking at the [commit history for the alert test directory](https://github.com/w3c/aria-at/commits/master/tests/alert) in the main branch of aria-at, I see the following versions for the alert plan:

1. V22.12.08
2. V22.04.14
3. V22.03.17
4. V21.10.15

In staging, When I open the add test plans to the test queue disclosure, choose alert, and look at the list of versions, the list is different. It is missing the Mar 17, 2022 version, and it has 3 others that are not in the above list: May 5, 2022, Mar 9, 2022, and Nov 18, 2021.
