### ISSUE TITLE
Add Test Plans to the Test Queue: Test plan dropdown includes two tests that are not in the tests directory of aria-at

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-at-app#581]
To reproduce:
1. Open Test Management page
2. Expand "Add Test Plans to the Test Queue"
3. Tab to test plan drop down.
4. Inspect values in the drop down.
5. Compare to [available aria-at test plans](https://github.com/w3c/aria-at/tree/master/tests).

Expected behavior: The test plans in the drop down match the plans available in the repository.

Actual behavior: There are two extra plans ("Alert" and "Modal Dialog") that appear at the bottom of the dropdown list.

**Comment by howard-e** [comment]
> Actual behavior: There are two extra plans ("Alert" and "Modal Dialog") that appear at the bottom of the dropdown list.

Seems there's a 3rd one here as well, "Checkbox Example (Tri State)" that's also at the bottom of the list. After it was renamed to "Checkbox Example (Mixed State)", looks like it wasn't properly mapped or removed. This "un-syncing" may also explain why it doesn't fall into the alphabetical order of the items above it

**Comment by alflennik** [comment]
We discussed this as a group this morning and considered some solutions to the issue. We decided that a good way to solve it would be to author a migration to update the obsolete directory names so they match the current directory names.

**Comment by ccanash** [comment]
This has been triaged and assigned to @howard-e

**Comment by howard-e** [comment]
> A follow-up PR will follow which will prevent the chance of this happening in the future.

Closing as this is solved but discussion on the follow-up PR may happen in #748.
