### ISSUE TITLE
AT Support Tables Embedding: Distinguish data not yet available from not applicable

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-at-app#598]
From [review of aria-practices PR 2569](https://github.com/w3c/aria-practices/pull/2569#issuecomment-1398008506), we need to provide more accurate copy in cells that do not contain data.

There are two reasons for a cell to not have data:
1. We have not yet tested the AT/Browser combination, e.g., JAWS/Firefox. 
2. The AT/Browser combination does not exist, e.g., JAWS/Safari. 

The copy in cells with no data should be:
* If the AT/Browser combination will be tested in the future, use the string "Data Not Yet Available" 
* If the AT/Browser combination does not exist, use the string "Not Applicable". 

There are other functions of the app that will need to reference data about valid AT/Browser combinations. So, we will need to determine how we want to represent these relationships in the data model.

**Comment by howard-e** [comment]
Work being done in #583 should address this

**Comment by howard-e** [comment]
Reopening until change is included in production.

**Comment by ccanash** [comment]
This change is already in production. cc @mcking65

**Comment by mcking65** [comment]
fixed by #583
