### ISSUE TITLE
Define valid AT + Browser combinations

### ISSUE THREAD

**Issue by howard-e** [w3c/aria-at-app#625]
Following up from a discussion in #583. There are potential risks to the application not explicitly outlining valid AT and Browser combinations.

While I'm unsure if there are use cases where the application would want to intentionally avoid this restriction, there is still a need to know which combinations are considered as "valid" in the cases where the restriction is required:

> Something of note is that while this solution does work under the ideal happy case, it is also pretty easy to get through (in the absolute rarest case of an admin overlooking several reviews or the process), and this also has nothing to do in particular with this PR.

> Example being that going to `/embed/reports/<plan>`, it correctly notes that the combination of JAWS + Safari is `Not Applicable` but I am still able to submit a JAWS + Safari combination from the Test Queue, push it all the way through to `CANDIDATE` or `RECOMMENDED` and a percentage value is displayed for JAWS + Safari even though it previously said `Not Applicable`. 

> I think we recently discussed this internally and the question would be how can we explicitly define valid Browser + AT Combinations, to be ideally used at the point when a Test Plan is being added to the Queue to prevent invalid combinations from being added? And potentially added as an additional safeguard for this embedded report?

_Originally posted by @howard-e in https://github.com/w3c/aria-at-app/pull/583#pullrequestreview-1371262760_

**Comment by ccanash** [comment]
This corresponds to P0: P0: Single-page view of test plan.
