### ISSUE TITLE
Display minimum review requirements notice on test plans

### ISSUE THREAD

**Issue by lolaodelola** [w3c/aria-at-app#627]
The Working Mode states that we should ensure there are at least 2 testers which have submitted (non-conflicting) results for their respective Test Runs. Should we add some highlighted piece of information displaying this consideration?

**Comment by mcking65** [comment]
Ensuring the appropriate amount of data is generated and review is completed for each test plan is a well-understood admin responsibility. It is not important that we provide reenforcement of this responsibility in the UI.
