### ISSUE TITLE
Provide additional phase timeline information for test plans in app flow

### ISSUE THREAD

**Issue by lolaodelola** [w3c/aria-at-app#628]
- For candidate test plan review, we are tracking the aging time of a test result for the 180 day period of candidacy, the 120 day window for AT developers to raise issues, and the 60 days window for collaboration between the test admin, test developer, and the AT developer. We (@howard-e & I) recommend displaying that time on the result page, linking to the relevant explanation of the window in the working mode, and annotating the times with relevant context. For example:

  - Make it clear to the admin that the Test Plan hasn't yet reached the proposed time for them to promote the plan to RECOMMENDED.
  - Show what the options if issues remain open after 180 days

- Similarly for Recommended test plans, we are tracking the 120 days of this phase. We (@howard-e and I) recommend reporting the time left in the UI.
- Similarly for [Issue Triage for Recommended Test Reports](https://github.com/w3c/aria-at/wiki/Working-Mode-Scenario-Support-Analysis#phase-issue-triage-for-recommended-test-reports) number 1. 
- We also recommend annotating the status summary section when there are issues open for that test plan.

**Comment by mcking65** [comment]
At this time, we can manage deadlines more manually. We are currently displaying target dates and have a wayto update them. That is sufficient for the current state of the project. I would prefer we prioritize other issues that are on the critical path.

**Comment by lolaodelola** [comment]
Thanks @mcking65. @howard-e I think this answers the questions in the doc about displaying wait times in the app.

**Comment by mcking65** [comment]
> * For candidate test plan review, we are tracking the aging time of a test result for the 180 day period of candidacy

180 is the minimum number of days the working mode suggests that a plan should be in candidate review. It is not related to test results, and it is not limited to a single version of the plan. For example, if V1 enters candidate review on Jan 1, the soonest an admin should advance any version of that plan to recommended is June 30. V1 might be deprecated by V2 prior to June 30. That would not reset the clock. It would still be fine if the admin advanced V2 to recommended on June 30.

>the 120 day window for AT developers to raise issues

This is more of a hope than reality right now. The process isn't functioning at that level yet.

>and the 60 days window for collaboration between the test admin, test developer, and the AT developer.

There is no 60 day window. If collaboration is happening, the working mode suggests that it should continue as long as needed.

>We (@howard-e & I) recommend displaying that time on the result page, linking to the relevant explanation of the window in the working mode, and annotating the times with relevant context.

Given that such parameters in the working mode could change over time, it is best to show information that is not based on these specific parameters. The current design enables the admin to set targets for candidate review. Showing information related to the targets can be helpful, and it doesn't depend on specific working mode parameters.

> * Similarly for Recommended test plans, we are tracking the 120 days of this phase. We (@howard-e and I) recommend reporting the time left in the UI.

There is not a 120 day limit on recommended phase. It is essentially infinite.

> * Similarly for [Issue Triage for Recommended Test Reports](https://github.com/w3c/aria-at/wiki/Working-Mode-Scenario-Support-Analysis#phase-issue-triage-for-recommended-test-reports) number 1.
> * We also recommend annotating the status summary section when there are issues open for that test plan.

Good catch! This should be part of #648. In the recommended phase column, if there are open issues, we should show the number of open issues. And, there should probably be a warning of some kind that appears at the top of the page if any recommended plans have open issues. I opened #720 to cover this requirement.

**Comment by ccanash** [comment]
Closed as this will be covered by #720
