### ISSUE TITLE
Set a status of "R&D Complete" for new test plan versions

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-at-app#634]
#### Problem

* The test plan life cycle described in #950 prescribes that there may be only one draft version of a plan.
* If a plan is in the test queue and has some test results, updating its version requires processing to determine what data can be preserved.
* We want the status summary table on the test management page to show all plans available in the w3c/aria-at#master branch.
* Thus, merging a new test plan version to w3c/aria-at#master cannot make that version draft because we would not want the merge operation to somehow depend on also executing the data preservation process.

#### Solution

When a new test plan version becomes available on the test management page, set its status as "R&D Complete". Then, the test admin can advance that version to draft within the aria-at app UI and complete the data preservation step if it is needed.

**Comment by mcking65** [comment]
Related to #580 and #622.

**Comment by lolaodelola** [comment]
We'll triage this internally & let you know who'll be working on it.

**Comment by lolaodelola** [comment]
@howard-e will be working on this task this sprint & we'll be merging #622 too.

**Comment by mcking65** [comment]
Testing in staging, this is working as expected.

**Comment by ccanash** [comment]
Released today
