### ISSUE TITLE
P0: Show the most advanced phase this plan has completed

### ISSUE THREAD

**Issue by lolaodelola** [w3c/aria-at-app#658]
_Related to #648: Overall Status Column Details._

Show the most advanced phase this plan has completed using the following logic:

- If there is a recommended version, show string "Recommended on DATE" where DATE is the most recent date on which a version of the plan was advanced to recommended.
- else If there is a candidate version, show string "Candidate on DATE" where DATE is the most recent date on which a version of the plan was advanced to candidate.
- else If there is a draft version, show string "Draft on DATE" where DATE is the most recent date on which a version of the plan was advanced to draft.
- else if R&D is complete, show string "R&D Complete on DATE" where DATE is the date from the version identifier of the version that is currently ready for draft review.

**Notes:**

- dates are sufficient; no need for time stamp.
- this column is used in the default sort order described below. The sort function of this column would return the table to its default state.

**Comment by ccanash** [comment]
Closing as this will be done within #652
