### ISSUE TITLE
P0: Adding complete date for plans that have left R&D

### ISSUE THREAD

**Issue by lolaodelola** [w3c/aria-at-app#659]
_Related to #648:R&D Status Column Details._

If the latest version of the plan is in the draft, candidate, or recommended phase, show string "Complete on DATE" where DATE is the date from the VERSION_STRING of the version that most recently advanced to draft.

**Comment by ccanash** [comment]
Closing as this will be done within #652

**Comment by howard-e** [comment]
Already covered by #652
