### ISSUE TITLE
P0: "Advance to Candidate" button

### ISSUE THREAD

**Issue by lolaodelola** [w3c/aria-at-app#664]
_Related to #648: Draft Status Column Details._

If there is a version currently in the draft phase and required reports are complete and user is an admin, show "Advance to Candidate" button. Note that:

- If there is an earlier version that is candidate and that version has some test plan runs in the test queue, this button will run the process for updating existing reports and preserving data for tests that have not changed.
- if there is an earlier version in the candidate phase, this button will sunset that version. This will also sunset any reports completed using that version.

**Comment by ccanash** [comment]
Closing as this will be done within #652
