### ISSUE TITLE
P0: Show version for candidate phase plan

### ISSUE THREAD

**Issue by lolaodelola** [w3c/aria-at-app#668]
_Related to #648: Candidate Status Column Details._ 

If there is a version currently in the candidate phase, show link with text "Version VERSION_STRING" and target the single-page view of the plan. Example: [Dec 8, 2022](https://aria-at.netlify.app/review/alert.html)

The link needs to be able to target a specific commit. The version of the plan that is "R&D Complete" will always be at the head of the main branch. However, if there is an earlier version of that plan that is in a later phase, it will be at an earlier point in the revision history.

**Comment by ccanash** [comment]
Closing as this will be done within #652
