### ISSUE TITLE
P2: Table sorting

### ISSUE THREAD

**Issue by lolaodelola** [w3c/aria-at-app#677]
_Related to #648: Table Sorting. Also #654 and #657_

- First sort by overall status descending: recommended plans, then candidate plans, then draft plans, then R&D complete plans.
- Then sort by test plan name ascending.

Why?

- In the near term, before filters are implemented, this will put the most important admin work near the top.
- In the long term, This will show all users an alphabetical list of all recommended plans at the top and provide access to the history of those plans.

**Comment by ccanash** [comment]
Closing as this will be done within #652
