### ISSUE TITLE
Database maps which browsers have reporting required for draft and recommended phases (P0)

### ISSUE THREAD

**Issue by lolaodelola** [w3c/aria-at-app#681]
_Related to #648: Required Reports Definition (Please see this section for additional context)._

<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(31, 35, 40); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">The draft and recommended phases will each require reports using a specific set of AT/browser pairs. At this time, the pairings for which reporting is required are as follows.</p>

Phase | AT | Browser
-- | -- | --
Draft | JAWS | Chrome
Draft | NVDA | Chrome
Draft | VoiceOver for macOS | Safari
Recommended | JAWS | Chrome
Recommended | JAWS | Firefox
Recommended | NVDA | Chrome
Recommended | NVDA | Firefox
Recommended | VoiceOver for macOS | Safari
Recommended | VoiceOver for macOS | Chrome

**Comment by mcking65** [comment]
This appears to be as complete as it can be for now. See comments in #758 about #791 and #792. Since the latter two issues are open, this issue can be mark resolved after deployment.

**Comment by ccanash** [comment]
Completed
