### ISSUE TITLE
P0: Add "Advance to Draft" button for admins for completed R&D plans

### ISSUE THREAD

**Issue by lolaodelola** [w3c/aria-at-app#684]
_Related to #648:R&D Status Column Details._

If the latest version has completed R&D and has not yet been advanced to draft review and the current user is an admin, show "Advance to Draft" button. Note that:
  - If there is an earlier version that is draft and that version has some test plan runs in the test queue, this button will run the process for updating existing reports and preserving data for tests that have not changed.
  - if there is an earlier version in the draft phase, this button will sunset that version. This will also sunset any reports completed using that version.

**Comment by ccanash** [comment]
Closing as this will be done within #652
