### ISSUE TITLE
Data Integrity Strategy for Reports

### ISSUE THREAD

**Issue by lolaodelola** [w3c/aria-at-app#689]
We need to ensure there's a robust data integrity strategy to ensure the accuracy of the data in reports. Some questions to discuss:

- How do we know the data does not currently include errors?
- How are we ensuring that an app or database update isn't creating errors in the reports?
- What queries are performed before and after a change to ensure anomalies are not present?
- How are we double checking that the data in the reports is internally consistent?
    -  Is the total number of assertion verdicts for all reports generated from a given plan consistent?
- Does the number of failing verdicts + number of passing verdicts = total verdicts?

**Comment by lolaodelola** [comment]
The action item for me was to compose a list of checks we might already be doing. After review, our tests are predominantly unit tests for actions that can be performed in the app. The level of testing we’d need would be for environment changes which would include pre/post deployment.

We don’t have any tests that check the environment is consistent between deploys.

As the definition of this issue has changed since I first wrote it, @mcking65 would you be able to provide/link to an example where the data changed between deploys?

**Comment by ccanash** [comment]
Closing this as no longer valid @mcking65
