### ISSUE TITLE
please add me

### ISSUE THREAD

**Issue by stevefaulkner** [w3c/aria-at-app#706]
i would like to participate

**Comment by jscholes** [comment]
Hi @stevefaulkner, thanks for your interest in helping out!  Just to clarify, are you asking to be added as:

* a tester, i.e. someone who will execute screen reader tests and record results;
* an AT vendor representative who will evaluate proposed test plan versions and either approve them or propose changes; or
* both?

**Comment by stevefaulkner** [comment]
@jscholes both, but mostly the latter

**Comment by jscholes** [comment]
@stevefaulkner I've added you in https://github.com/w3c/aria-at-app/pull/707.  @howard-e Please close this issue once any needed deployment has happened to reflect these changes.

**Comment by howard-e** [comment]
> @stevefaulkner I've added you in #707. @howard-e Please close this issue once any needed deployment has happened to reflect these changes.

Noted, thanks @jscholes. Will share when that's complete

**Comment by howard-e** [comment]
@jscholes @stevefaulkner the deployment has been completed
