### ISSUE TITLE
Data Management page shows incorrect test plan version numbers for alert test plan

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-at-app#716]
This bug appears in the sandbox on July 28.

To reproduce:
1. Load data management page.
2. Read the row for the alert test plan.
3. Compare the test plan version number in the draft review column to the version number in the candidate review column.
4. Version in draft review is V22.05.05
5. Version in candidate review is V22.12.08.

![image](https://github.com/w3c/aria-at-app/assets/7241781/f0ec2abc-ad59-4cf8-ab8c-ce1bb3900096)

**Actual results:**
* According to the [commit history for the alert test plan](https://github.com/w3c/aria-at/commits/master/tests/alert), The alert plan does not have a version with number V22.05.05.
* The version currently in draft review is older than the version that is in candidate review.

**Expected results:**
* The only test plan version numbers that could appear in the table for alert would be one of V22.03.17, V22.04.14, or V22.12.08.
* The version of a plan that is in candidate review should always be older than a version that is in draft review or R&D complete. When a newer version of a plan advances to a phase where an older version is active, the older version is deprecated.

**Comment by mcking65** [comment]
Note there are some other test plans where the version that appears in draft review is older than the version in candidate review:
* Disclosure Navigation Menu Example
* Radio Group Example Using aria-activedescendant

**Comment by howard-e** [comment]
> * The only test plan version numbers that could appear in the table for alert would be one of V22.03.17, V22.04.14, or V22.12.08.
> * The version of a plan that is in candidate review should always be older than a version that is in draft review or R&D complete. When a newer version of a plan advances to a phase where an older version is active, the older version is deprecated.

Should be addressed in https://github.com/w3c/aria-at-app/pull/713/commits/6efe32c352b2199f4fb3e9b110aad87bdf3e008b

> Note there are some other test plans where the version that appears in draft review is older than the version in candidate review:
> 
> * Disclosure Navigation Menu Example
> * Radio Group Example Using aria-activedescendant

The same fix should also apply here.

**Comment by mcking65** [comment]
Confirmed that this issue is fixed in staging and that it can be closed after deployment.

It is important to note that that I cannot test the condition where a specific plan has multiple active versions because that condition is not present in the staging data, and I can't create it without interfering with production data. We will need to pay attention to the system behavior as we start merging new versions of test plans in prod during the test plan refactoring.

**Comment by ccanash** [comment]
Released

**Comment by ccanash** [comment]
@howard-e and @alflennik  just flagging Matt's comment about not being able to test the condition where a specific plan has multiple active versions so that you keep it in mind.
