### ISSUE TITLE
Test plan status summary table incorrectly shows covered AT as "N/A"

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-at-app#717]
This bug appears in the sandbox on July 28.

To reproduce:
1. Open the data management page.
2. In the test plan status summary table, scroll down to the row for "Action Menu Button Example Using element.focus()"
3. Observe the covered AT column value for that row and all subsequent rows.

![image](https://github.com/w3c/aria-at-app/assets/7241781/39de38a4-27bd-485e-8dd6-13ebd795b840)

**Actual Result:** The covered AT values are "N/A"

**Expected Result:** The covered AT values are "JAWS, NVDA and VoiceOver for macOS"

**Comment by howard-e** [comment]
https://github.com/w3c/aria-at-app/pull/713/commits/f61f02ea80f8181189a6871ad3662285f868abdf addresses this

**Comment by mcking65** [comment]
Confirmed that this issue is fixed in staging and that it can be closed after deployment.

**Comment by ccanash** [comment]
Released to production
