### ISSUE TITLE
Add Test Plan Versions page that provides the complete version history for a test plan (P1)

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-at-app#719]
In the test plan status summary table on the data management page, each test plan name will link to a page that provides access to information about all versions of that test plan. That page will include the following information.

1. A link to the commit history for the test plan.
1. A summary table listing some high-level information about each version.
1. A GitHub issues table listing feedback issues and the issue documenting R&D for the plan.
1. A timeline table listing all working mode events for the test plan.
1. A Section for each test plan that provides detailed information for each version and the timeline for that version.

Following are descriptions of requirements for the page and each of the above features.

Here is a zip of an HTML file containing a page mockup. [Test Plan Versions Page Mockup.zip](https://github.com/w3c/aria-at-app/files/12210331/Test.Plan.Versions.Page.Mockup.zip)

Notes about data in the mockup:
* Links to GitHub represent real data
* Links to single page view and reports do not contain valid href values
* Most of the phase change dates are real, but some are made up because I didn't have a way to figure out the actual date; they are approximate.

#### Page title

The `h1` of the page has format `TEST_PLAN_NAME Test Plan Versions`. Example:

~~~
<h1>Alert Test Plan Versions</h1>
~~~

#### Test plan commit history link

A link to the commit history for the repository path containing the test plan. The link text provides the path name. For example:

>[Commit History for aria-at/tests/alert](https://github.com/w3c/aria-at/commits/master/tests/alert)

#### Versions summary table

Caption: Version Summary

Columns:
* Version: Plan version number, e.g., V22.12.08
* Latest Phase: Name of most recent phase. If deprecated, the string "Deprecated during PHASE_NAME"
* Phase Change Date: Date on which the working mode phase of the version changed

Sort order: Version number descending

#### GitHub issues table

Caption: GitHub Issues

Columns:
* Author: GitHub ID of issue author
* Issue: Link with text Issue ISSUE_NUMBER: ISSUE_TITLE
* Status: Open | Closed
* Created On: Date created
* Closed On: Date close or blank if not closed

Sort order: date created descending

#### Timeline table for all versions

Caption: Timeline for all versions

Columns:
* Date
* Event: One of the following:
    * VERSION_NUMBER R&D Complete
    * VERSION_NUMBER Draft Review Started
    * VERSION_NUMBER Candidate Review Started
    * VERSION_NUMBER Approved as Recommended
    * VERSION_NUMBER Deprecated

Sort order: date ascending

#### Test plan details sections

1. Heading level 2:
    * Text format: VERSION_NUMBER PHASE_NAME on DATE_OF_PHASE_CHANGE
    * Example: V22.12.08 Recommended on Jun 1, 2023
1. Link to commit:
    * Text format: Commit SHORT_HASH: COMMIT_TITLE
    * Example: [Commit 0928bcf: Alert and Radiogroup/activedescendent updates (#865)](https://github.com/w3c/aria-at/commit/0928bcf530efcf4faa677285439701537674e014)
1. Link to single page view of tests
    * Text format: View tests in VERSION_NUMBER
    * Example: View tests in V22.12.08
1.     Link to reports
    * Text format: View reports generated from VERSION_NUMBER
    * Example: View reports generated from V22.12.08
1. List of covered AT    
1. Timeline table
    * Caption text format: Timeline for VERSION_NUMBER
    * Caption example: Timeline for V22.12.08
    * 2 Columns: Date, Event
    * Event column values are one of:
        * R&D Complete
        * Draft Review Started
        * Candidate Review Started
        * Approved as Recommended
        * Deprecated
    *  Sorted by date ascending

**Comment by isaacdurazo** [comment]
Here's the mockup for this page.

@mcking65 There's not much new visually to be described. I kept the same styling we are using in the Data Management page. The only new thing is that I applied a "label design" to the word "Deprecated" to it fit with the rest of the design we use for the phases. This new "deprecated label" is in red. I also added some icons. I'll summarize here my suggestions for look and feel:

1. All Phases use the same "label" design previously used
2. The word "Deprecated" uses the existing phase label design and is in red
3. Commit links are accompanied by an icon representing the word "Commit". Github uses the same icon.
4. View links are accompanied by the universal icon that represents "open in new page/window". An arrow pointing out of a square.
5. Version numbers use the same subtle gray background and checkmark icon in dark gray.

![ARIA-AT - Test Plan Versions page](https://github.com/w3c/aria-at-app/assets/1379244/a059b1ad-9167-4fd1-973d-1e328468047a)

**Comment by mcking65** [comment]
thank you @isaacdurazo!!

**Comment by mcking65** [comment]
See #761. It should be resolved before closing this issue.

**Comment by mcking65** [comment]
Tested in staging. All requirements are now met. Beautiful work team!

**Comment by ccanash** [comment]
#761 is closed. REleased to prod
