### ISSUE TITLE
Advancing a test plan to recommended incorrectly changes the completion date for draft review

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-at-app#723]
Testing in staging on August 1.

To reproduce:
1. Open data management and find a test plan that has a version in the candidate review phase and does not have a version in draft review.
2. Make note of the draft review completion date.
3. Advance the plan to recommended.
4. Observe the draft review completion date.

**Expected Result:** The draft review completion date does not change.

**Actual Result:** The draft review completion date is set to the same date as the candidate review completion date.

Here are screen shots for this process for color viewer slider.

While V22.04.14 is in candidate review, the draft review completion date is April 9, 2022. (Note: there is something wrong with that data because the community group can't complete draft review of a plan that was merged to main on April 14 5 days before it was merged!)

![image of before](https://github.com/w3c/aria-at-app/assets/7241781/b07f9716-c016-445d-94c7-412207523685)

After promotion to recommended, the draft review completion date is Aug 1, 2023.

![image after advancement](https://github.com/w3c/aria-at-app/assets/7241781/9ee0b7b7-37b9-44d1-85a0-54598dac820a)

**Comment by mcking65** [comment]
Testing in staging; this issue is resolved.

**Comment by ccanash** [comment]
Released
