### ISSUE TITLE
Draft to Candidate dialog presents incorrect information about reports

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-at-app#724]
Found in staging on August 1.

Reproducing is not straightforward because it is not possible to know if the necessary conditions exist.

1. Open data management page.
2. Find a plan that has a version in draft review.
3. Press the button to advance to candidate review. I did this for "Action Menu Button Example Using aria-activedescendant".
4. Note dialog content. The dialog stated that there were reports for JAWS/Chrome, NVDA/Chrome, VoiceOver/Safari.
5. Press continue.

**Actual Results:**
* There are no reports.
* The test plan does not appear on the candidate tests page.

**Expected Results:**
* The advance phase confirmation dialog accurately communicates report status.
* All plans that are in candidate review appear on the Candidate Tests page.

Screenshot of reports page showing that the action menu button test plan is in candidate review but does not have any reports:

![image](https://github.com/w3c/aria-at-app/assets/7241781/1acbb8d5-bbed-4498-a8a3-b2076cbbf1af)

Screenshot showing the candidate tests page and the action menu button test plan is not listed:

![image](https://github.com/w3c/aria-at-app/assets/7241781/2fd17960-64bd-46d7-8b90-1410eb3a416c)

**Comment by mcking65** [comment]
Testing in staging, this issue is resolved. However, I opened a closely related issue #798.

**Comment by ccanash** [comment]
Released to prod
