### ISSUE TITLE
Add version string and remove change status button from test plan column on  Candidate Test page (P0)

### ISSUE THREAD

**Issue by ccanash** [w3c/aria-at-app#726]
Based on @mcking65  comment : https://github.com/w3c/aria-at-app/issues/709#issuecomment-1652493515  

- [x] Add test plan version to the test plan column (_VYY.MM.DD_)
- [x] Remove Change report status button from test plan column

**Comment by mcking65** [comment]
Verified that this is working as specified in staging. This issue can be closed after deployment.

**Comment by ccanash** [comment]
Released to prod.
