### ISSUE TITLE
Candidate test page: Remove Change Target Date button, Move Candidate Phase Start Date and Target Completion Date, change title (P1)

### ISSUE THREAD

**Issue by ccanash** [w3c/aria-at-app#727]
In Candidate test page : 

- [x] Move Candidate Phase Start Date and Target Completion Date out of test plan column into separate columns.
- [x] Change page title from "Candidate Tests" to "Candidate Review"

**Comment by mcking65** [comment]
Verified these changes are implemented correctly in staging. This issue can be closed after deployment.

**Comment by ccanash** [comment]
Released to prod.
