### ISSUE TITLE
Revise reports to show assertion priorities as MUST/SHOULD/MAY instead of REQUIRED/OPTIONAL 

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-at-app#737]
### Problem

Currently, many important AT behaviors that are not absolutely essential to usage of a pattern are classified with the assertion priority "Required". Similarly, the assertion priority "optional" does not allow reports to distinguish between important behaviors that an AT should exhibit and potentially helpful but less important behaviors that an AT may exhibit.

These two characteristics of the current two-tier assertion prioritization system are having two significant impacts on the progress and utility of the ARIA-AT project:
1. They are impeding development of consensus.
2. They make reports less useful to consumers who are evaluating the suitability of a pattern for a specific purpose. This impact will be magnified when ARIA-AT starts evaluating new and emerging ARIA features.

### Solution proposal

Align the assertion priorities with typical W3C normative requirement priorities of MUST, SHOULD, and MAY.

### Implementation plan

In all existing test data:
* assertion priority 1 will be interpreted as "MUST" instead of "REQUIRED"
* assertion priority 2 will be interpreted as "SHOULD" instead of "OPTIONAL"

In the future, when test plans are converted to the V2 test format, some assertions will have a priority of 3, which maps to "MAY".

Assuming #733 is implemented, two aspects of data reporting need to change:
1. Display of priority data in command results tables.
2. Columns in report summary tables.

### Changes to display of priority data in command results tables

In the tables specified by #733, there is a column for assertion priority. The data cells in that column need to show "MUST" for assertion priority 1 and "SHOULD" for assertion priority 2.

### Changes to columns in report summary tables

In [report tables](https://aria-at.w3.org/report/1090,1890,2215) that summarize results for each test using a specific AT and in a given browser:
* Change column heading "Required Assertions" to "MUST-DO Behaviors".
* Change column heading "Optional Assertions" to "SHOULD-DO Behaviors".
* Add a column "MAY-DO Behaviors".

**Comment by lolaodelola** [comment]
Hi @mcking65 I've added the agenda label so that we can discuss this further in the CG tomorrow. I understand it was discussed in a meeting while both Mike & I were away but I'd like to bring up some concerns we have as a group about the wording, particularly "MAY".

**Comment by ccanash** [comment]
Closing as released to production
