### ISSUE TITLE
Count problematic (unexpected) behaviors as assertion failures

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-at-app#738]
#### Problem

Currently unexpected or undesirable behaviors are tabulated separately from assertion failures. This hides their impact by preventing them from impacting top line support level numbers. This reduces the utility of AT support tables in the APG. A pattern could have 100% support of required assertions and thus look really good in the support table but then have problematic behaviors so severe that the pattern is unusable.

#### Solution

Note: The following solution assumes the system has been changed to use 3 assertion priorities as specified in #737.

To address these issues, this proposal suggests the following changes:
1. Change the description of these behaviors to "Other behaviors that create negative impacts"
2. For each other negative behavior collect two additional data elements:
    * Severity: high or moderate impact
    * A description of why the AT response exhibits the behavior.
4. In the reporting system, use the severity data collected to report on the following two assertions for every command in every test:
    * Other behaviors that create high negative-impacts are not exhibited
    * Other behaviors that create moderate negative-impacts are not exhibited

5. When reporting, do not report other negative behaviors in a column separate from assertions as is currently done. Instead, let any other negative behavior trigger failure for one of the above 3 assertions. 

Example: Consider the alert report for Test: Trigger an alert in reading mode.

The [current report](https://aria-at.w3.org/report/1890) includes two commands that each have two assertions. So, there are a total of 4 verdicts in the report for this test.

Test Name | Required Assertions | Optional Assertions | Unexpected Behaviors
--- | --- | --- | ---
Trigger an alert in reading mode | 4 of 4 passed | 2 of 2 passed | None

If we were to map the current optional assertion to a MAY-DO priority as described in #737, there would be 1 MUST-DO behavior and one MAY-DO behavior for each command.

Priority | Assertion
--- | ---
MUST | Text 'Hello' is conveyed
MAY | Role 'alert' is conveyed

If we were to add the two problematic behavior assertions described above to this list, each command would have 4 assertions, increasing the total number of verdicts for this test report from 4 to 8.

Priority | Assertion
--- | ---
MUST | Text 'Hello' is conveyed
MUST | Other behaviors that create high negative-impacts are not exhibited
SHOULD | Other behaviors that create moderate negative-impacts are not exhibited
MAY | Role 'alert' is conveyed

Thus instead of the above report, we would have:

Test Name | MUST HAVE Behaviors | SHOULD HAVE Behaviors | MAY HAVE Behaviors
--- | --- | --- | ---
Trigger an alert in reading mode | 4 of 4 passed | 2 of 2 passed | 4 of 4 passed

Very importantly, if  a high impact negative behavior were present for one command, then the MUST-have behavior support would drop from 100% (4/4) to 75% (3/4).

Test Name | MUST HAVE Behaviors | SHOULD HAVE Behaviors | MAY HAVE Behaviors
--- | --- | --- | ---
Trigger an alert in reading mode | 3 of 4 passed | 2 of 2 passed | 4 of 4 passed

If the high-impact problematic behavior occurred when Enter was pressed, using the results table design from #733, the failure would be reported as:

Enter Results (4 passed, 1 failed)

Priority | Assertion | Verdict
--- | --- | ---
MUST | Other behaviors that create high negative-impacts are not exhibited | Failed
MUST | Text 'Hello' is conveyed | Passed
SHOULD | Other behaviors that create medium negative-impacts are not exhibited | Passed
MAY | Role 'alert' is conveyed | Passed
MAY | Other behaviors that create low negative-impacts are not exhibited | Passed

#### App changes

- [ ] Modify the results collection form so that each behavior in the list of problematic behaviors has the following inputs:
    * A checkbox to indicate if the behavior occurred.
    * A select labeled "Impact" with values Low, Medium, and High. It is disabled if the checkbox is not checked and required if it is checked.
    * A text field labeled "Details" that is disabled if the checkbox is not checked and required if it is checked.
- [ ] Add problematic behavior assertions to the test results tables defined in issue 733.
- [ ] Remove unexpected behavior columns from reports and include the problematic behavior assertion results in the data for the MUST/SHOULD/MAY behavior columns.

**Comment by mcking65** [comment]
I didn't finish the to-do discussed in the Sep 7 meeting. I will target having this ready for the Sep 27 meeting.

**Comment by howard-e** [comment]
Based on previous discussions, the bottom of the task should also be edited as:

Enter Results (~4~ 3 passed, 1 failed)

Priority | Assertion | Verdict
--- | --- | ---
MUST | Other behaviors that create high negative-impacts are not exhibited | Failed
MUST | Text 'Hello' is conveyed | Passed
SHOULD | Other behaviors that create medium negative-impacts are not exhibited | Passed
MAY | Role 'alert' is conveyed | Passed
~MAY~ | ~Other behaviors that create low negative-impacts are not exhibited~ | ~Passed~

#### App changes

- [ ] Modify the results collection form so that each behavior in the list of problematic behaviors has the following inputs:
    * A checkbox to indicate if the behavior occurred.
    * A select labeled "Impact" with values ~Low, Medium, and~ High and Moderate. It is disabled if the checkbox is not checked and required if it is checked.
    * A text field labeled "Details" that is disabled if the checkbox is not checked and required if it is checked.
- [ ] Add problematic behavior assertions to the test results tables defined in issue 733.
- [ ] Remove unexpected behavior columns from reports and include the problematic behavior assertion results in the data for the MUST/SHOULD/MAY behavior columns.

**Comment by mcking65** [comment]
Testing in staging, this is most of the way there. I found the following problems. I believe these should be fixed before deploy because one affects the understandability of reports and one affects accessibility of the collection form.

1. On the collection form, keyboard access is broken in the group of additional undesirable behaviors. If you mark the "Yes radio" and then tab, you can only tab to the first checkbox. The subsequent behaviors are not keyboard accessible.
2. In the meeting where reviewed the wording, we decided to use the word "Severe" instead of "High".
3. In the runner after results are submitted and on the report page, the details of the additional undesirable behaviors are still labeled "Unexpected Behaviors:". We should change that wording so readers can directly tie the content back to the assertions. I think the label should be "Other behaviors that create negative impact:". Instead of a list, the details would be easier to read in a 3-column table with columns for "Behavior", Details", and "Impact".

**Comment by mcking65** [comment]
Because the problems are significant enough to block deployment, changing status to in progress.

**Comment by mcking65** [comment]
Retested in staging and all the problems listed in my previous comment are resolved. Thank you!!
