### ISSUE TITLE
Should not be able to add deprecated test plan versions to the test queue

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-at-app#741]
Problem observed in staging.

In staging, the color viewer slider test plan has only one active version (V22.04.14). All earlier versions are deprecated.

![image of data management page showing color viewer slider row](https://github.com/w3c/aria-at-app/assets/7241781/d185546d-9ed0-415a-8b35-ab5d59f18076)

It should not be possible to add versions earlier than V22.04.14 to the test queue because they are all deprecated. Yet, the deprecated versions show up in the add to queue dialog.

![image of add to queue dialog showing deprecated versions of slider test plan](https://github.com/w3c/aria-at-app/assets/7241781/a1a90fc1-69bc-4e14-a481-3315e31eb47a)

**Comment by ccanash** [comment]
We will triage this

**Comment by mcking65** [comment]
Verified fixed in staging. Thank you @howard-e.

**Comment by ccanash** [comment]
Released to prod
