### ISSUE TITLE
Show test plan version number instead of publication date in Test Queue

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-at-app#754]
The test plan column of  tables on the Test Queue page are still showing:

>Action Menu Button Example Using aria-activedescendant
>Published Mar 17, 2022 at 6:34:51 pm UTC

Instead of  the plan name and version like is shown in candidate review:

>Action Menu Button Example Using aria-activedescendant
>V22.03.17 (15 Tests)

Show version number instead of date on the Test Queue page.

**Comment by mcking65** [comment]
Verified fixed in staging. This issue can be closed after deployment.

**Comment by ccanash** [comment]
Released to prod
