### ISSUE TITLE
Mark as final button should not be shown for runs in the test queue that have conflicts

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-at-app#755]
It should not be possible to mark a report final if conflicts exist. There are test plans with conflicts in the test queue in staging, and the mark as final button is present.

![image showing a mark as final button next to 7 conflicts](https://github.com/w3c/aria-at-app/assets/7241781/dc456fd8-e8ca-46b5-b369-5f49fa2abd35)

**Comment by howard-e** [comment]
https://github.com/w3c/aria-at-app/commit/fffdb62c696bebfe48d3913cf8f03f30dedd9970 has been pushed to #688 and the sandbox and staging environments.

**Comment by mcking65** [comment]
Tested in staging and this specific issue is resolved. During testing, found similar problems that I documented in #787.

This issue can be closed as resolved after deployment.

**Comment by ccanash** [comment]
Released to prod
