### ISSUE TITLE
Reporting Status Dialog contains misleading, superfluous heading

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-at-app#756]
The report status dialog has 2 level 2 headings. The first heading is correct. the second heading that appears just before the table contains incorrect content that is misleading. It needs to be removed.

For example, the Report Status dialog for the Color Viewer Slider Test Plan has:

Correct heading:

>Report Status for the Color Viewer Slider Test Plan

Incorrect heading to remove:

>Reports for Draft Alert Test Plan

![image](https://github.com/w3c/aria-at-app/assets/7241781/ccc5c320-493a-4b0e-a918-93955ecc6e27)

**Comment by mcking65** [comment]
I think this is a remnent of the fact that I used the alert test plan as an example in the mockups for issue #648. The content was interpreted literally instead of as an example. Sorry for the lack of clarity.

I marked this as p0 because the heading is misleading and confusing.

**Comment by stalgiag** [comment]
Thanks for pointing this out. Will fix now!

**Comment by howard-e** [comment]
This has been added to the staging and sandbox environments

**Comment by mcking65** [comment]
I tested this right after the fix was deployed but didn't comment in the issue. Making a note here that the fix is still good in staging.

Thank you @stalgiag .
