### ISSUE TITLE
Keyboard and focus related accessibility issues in report status dialog

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-at-app#757]
The report status dialog is very close to the mark on accessibility, but there are a few issues that are rather consequential:

1. Focus is initially placed on the dialog.
2. You can't tab backward through the dialog.
3. Tab is not fully trapped; it leaves the dialog and goes into browser chrome, e.g., address bar.

Please remove tabindex=-1 from the dialog element. Set tabindex=-1 on the heading and initially place focus there when the dialog opens. If you don't like how that looks from a design perspective, It would be OK to visually draw focus around the entire dialog instead of just the heading.

Make sure that it is possible to both Ttab backwards and forwards through the dialog tab sequence, and ensure that focus does not leave the dialog. For an example, see [Modal Dialog Example | APG | WAI | W3C](https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/dialog/).

**Comment by howard-e** [comment]
@mcking65 said in #785:

> Accessibility issue: Like several of the other dialogs, the tab sequence is broken. Tabbing from the save button should move focus to the date input. Back tabbing from the date input should move focus to the save button.

**Comment by mcking65** [comment]
Tested this in staging, and all the problems listed in this issue are resolved.

During testing, I found a different accessibility issue that I apparently overlooked earlier: #811.

**Comment by ccanash** [comment]
Closing as released to production
