### ISSUE TITLE
Fix required reports data

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-at-app#758]
The report status dialogs are showing 6 reports required during candidate review. Only 3 are required for draft and candidate:

1. jaws/chrome
2. NVDA/Chrome
3. VoiceOver/Safari
3 more are required in recommended phase:

1. JAWS/Firefox
2. NVDA/Firefox
3. VoiceOver/Chrome

**Comment by howard-e** [comment]
This must have been a misunderstanding for the condition when updating to `Recommended`.

1. The thought was those additional 3 were required BEFORE being able to transition to `Recommended`.
2. That means the `Required Reports` button should also be available on the `Recommended Version` cell and it will most likely say `Some Required Reports Missing`, when initially transitioned to.

@mcking65 if 1 was a false assumption and 2 is the expectation, then #764 addresses this. Could you confirm?

**Comment by mcking65** [comment]
> This must have been a misunderstanding for the condition when updating to `Recommended`.
> 
> 1. The thought was those additional 3 were required BEFORE being able to transition to `Recommended`.

No, we can advance to recommended without them.

> 2. That means the `Required Reports` button should also be available on the `Recommended Version` cell and it will most likely say `Some Required Reports Missing`, when initially transitioned to.

Definitely, that is the expectation. There are other conditions where it will appear in the recommended phase column. There is a to-do in issue #648 for me to work with you on the algorithm for that.

> @mcking65 if 1 was a false assumption and 2 is the expectation, then #764 addresses this. Could you confirm?

Confirmed.

**Comment by howard-e** [comment]
> > @mcking65 if 1 was a false assumption and 2 is the expectation, then #764 addresses this. Could you confirm?
> 
> Confirmed.

Thanks! #764 has been added to the sandbox and staging environments

**Comment by mcking65** [comment]
Confirmed that the issue is resolved in staging, at least for draft and candidate test plans.

**Comment by ccanash** [comment]
released. #792 and #791 will be tackled separately.
