### ISSUE TITLE
It should be impossible to advance to candidate if required reports are missing

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-at-app#762]
The data management page shows some test plans in candidate review that have missing required reports. This should not be possible. three reports are required before a plan can move from draft to candidate review. Once in candidate review, there are no additional reporting requirements. Additional reporting is not required until after a plan is recommended.

In the staging environment, two plans that are in candidate review and showing that required reports are missing are:
* Action Menu Button Example Using aria-activedescendant
* Disclosure Navigation Menu Example

![image](https://github.com/w3c/aria-at-app/assets/7241781/f44e3736-b788-446b-9ecb-1176adef9dd3)

**Comment by howard-e** [comment]
@mcking65 this is only slightly related to #758, in that some of the required reports shown as missing could be getting incorrectly shown.

But In the instance that it isn't, then this is another consequence of the migration. It picked up the previous `TestPlanReport.status` (which no longer exists) as `CANDIDATE`, so it was marked as final and the parent new `TestPlanVersion.phase` was pushed to `CANDIDATE` to support the this new structure. We acknowledged that the phases of some TestPlanVersions won't be possible in the future now that conditions such as required reports will prevent that ,through the server and client operations. We could push both of those TestPlanVersions back to DRAFT for "correctness" in the staging and sandbox environments, but it may not also be necessary soon, given that all the required reports are now included in the [production data](https://aria-at.w3.org/reports).

Also yay for [an empty Test Queue!](https://aria-at.w3.org/test-queue)

**Comment by mcking65** [comment]
OK then, anything that is not addressed by #758 will be overcome by events. We will add the missing reports or bring a new version of the plan forward or both.
