### ISSUE TITLE
Add collapsible areas to Test Plan Versions History Page

### ISSUE THREAD

**Issue by howard-e** [w3c/aria-at-app#769]
@mcking65 said in #761:

> As I go through this page, given the length of sections, I wonder if it would be beneficial for all level 2 headings after the version summary to be disclosures that are collapsed by default, e.g.:
> 
> `<h2><button aria-expanded="false">GitHub Issues</button></h2>`
> 
> Then people could easily see what is on the page without scrolling down.
> 
> Note that details/summary can't be used for this because you can't wrap a summary in a heading, and the heading navigation is super important.

**Comment by mcking65** [comment]
Tested in sandbox on 12/3. Great improvement, thank you!

This issue can be closed when deployed to prod.
