### ISSUE TITLE
Test plan version history shows incorrect deprecation dates

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-at-app#777]
Deprecation dates are incorrect in the test plan version histories.

For example:
* [Action Menu Button Example Using aria-activedescendant Test Plan Versions | ARIA-AT](https://aria-at-staging.w3.org/data-management/menu-button-actions-active-descendant) shows that v2021.10.13 was deprecated on October 13, 2021, which is not possible because there was not a new version that could have deprecated it until march 17, 2022.
* [Alert Example Test Plan Versions | ARIA-AT](https://aria-at-staging.w3.org/data-management/alert) shows that V21.10.15 was deprecated on Oct 15, 2021, which is not possible because there was not a new version that could have deprecated it until Dec 8, 2022.

**Comment by mcking65** [comment]
Now looks good in staging! Thx @howard-e and @evmiguel!

**Comment by ccanash** [comment]
Released
