### ISSUE TITLE
Test plan version history shows incorrect text when a plan in R&D Complete phase is deprecated

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-at-app#778]
If a test plan is deprecated before starting draft review, the text in the "Latest Phase" column of the "Version Summary" table is:

>Deprecated during R&D review

![image](https://github.com/w3c/aria-at-app/assets/7241781/da3c1957-586e-4718-a00f-a759a4a3e4f1)

There is not a phase named "R&D Review".

However, following the spec I wrote in #719 would have not been much better. The spec says to use the text "Deprecated during PHASE_NAME", which would have created the text:

>Deprecated during R&D

That wouldn't have been accurate and would have been confusing. The spec I wrote in in #719 is fine if the phase is draft review or candidate review, but it is not very good for R&D or Recommended.

I recommend using the following text strings for when plans are deprecated in either of these two phases.

If a test plan is deprecated after R&D is complete and before draft review is started, use the string "Deprecated before draft review started".

If a test plan is deprecated after it has been approved as recommended, use the string "Deprecated after being approved as recommended".

**Comment by mcking65** [comment]
Thank you @alflennik  and @howard-e! This is working well in staging now.

**Comment by ccanash** [comment]
Released to prod
