### ISSUE TITLE
add test plan status and app navigation banner to test plan review page

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-at-app#788]
On the test plan review page, example screenshot below, it is important that readers can determine the current working mode status of the test plan and can readily discern that this page is part of the aria-at app. They need to be able to get from this page to the version history for the test plan as well as other pages in the app. These requirements are particularly important for this page because it is a page that may be shared in contexts outside the app, e.g., issues or email.

Specific requirements are provided below. Note that they use language that is a slightly more verbose than in some other pages. The language is intended to help give people who have little or no familiarity with the ARIA-AT working mode some idea of the current status and history of this test plan. Like the reports, this page is one of the pages in the app that may be shared with people who are not directly involved with the project and are looking at this information with a singular purpose, e.g., an AT developer assigned to a bug, an AX specialist asked to learn about expected screen reader behaviors for a specific widget.

![Screenshot of color viewer slider test plan review page](https://github.com/w3c/aria-at-app/assets/7241781/8a23c773-c404-40f3-b6b2-ed630e75475a)

#### Add aria-at banner

Add the site-wide banner that includes top-level navigation to the top of the page.

#### Add link to version history page

Under the H2 and before the commit summary, add a link named "View all versions of this test plan".

Present this link as the first item in an unordered list. Subsequent list items are described below.

#### Add current test plan working mode progress and status

Add elements to the above mentioned list that show the current and previously completed working mode phases for this plan using the following text. 

* If current phase is R&D Complete, add list item with string "This version is a proposed  draft; ARIA-AT review processes have not yet started."
* If draft review has started:
     * Replace prior list item text with "R&D complete on COMPLETION_DATE for this version."
    * Add list item with text "ARIA-AT draft review process started on START_DATE for this version."
* If candidate review has started, add a list item with text "ARIA-AT candidate review process started on START_DATE for this version."
* If the version is recommended, add element with string "ARIA-AT Community Group approved this version as recommended on RECOMMENDED_DATE."
* If version is deprecated, add element with string "This version was deprecated on DEPRECATION_DATE. Most recent version is VERSION_STRING_LINK." where VERSION_STRING_LINK is a link to the test plan review page for the most recent active version.

#### Emphasize deprecated status in heading

If the version is deprecated, add "Deprecated " to the start of the H2 before the word "Version" and visually style the word and/or heading to draw attention to the fact that this version of the plan is currently deprecated.

#### Example

Following is an example of the list generated using the above spec as applied to [V22.04.14 of the color viewer slider test plan](https://aria-at-staging.w3.org/test-review/1c6ef2fbef5fc056c622c802bebedaa14f2c8d40/horizontal-slider).

* [View all versions of this test plan](https://aria-at-staging.w3.org/data-management/horizontal-slider).
* R&D completed on Apr 14, 2022 for this version.
* ARIA-AT draft review process started on Apr 14, 2022 for this version.
* ARIA-AT candidate review process started on Apr 15, 2022 for this version.

---

_Originally posted by @mcking65 in https://github.com/w3c/aria-at-app/issues/679#issuecomment-1662861833_

**Comment by mcking65** [comment]
@ccanash 

This has status to-do but the changes appear to be in sandbox.

**Comment by ccanash** [comment]
closing as in production and will address it on #789
