### ISSUE TITLE
Update test queue to support generating reports that require a specific AT or browser version

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-at-app#791]
#### ARIA-AT goal

One goal of the ARIA-AT working mode specific to test plans in the recommended phase is to keep their interop reports current. That means, for each AT/Browser combo that has a report, generate a new report when a new version of an AT or browser is released. In addition to keeping data current, over time, this will also create data that can be used to publish trend charts.

The CG has not yet defined criteria for which releases of AT or browsers would updates. That criteria could change over time.

As long as reporting involves a substantial amount of manual work, the community group may choose to be fairly selective about the releases for which new reports are required. For example, we could require new reports only for major AT releases and not for new browser releases. Any recent browser version could be considered sufficient in that scenario.

#### Test queue design update objective

Enable the test queue to include test plan runs that require a specific version of an AT or browser. If a test plan run does not require a specific version of either AT or browser, clearly indicate that any recent version is sufficient.

#### Design discussion

Should we fit version requirements into the current tables? Or, should we use this issue to drive a redesign of the information architecture of the queue?

Expedient option A: Add a table column "Version Requirements". Show the AT /browser name and versions required.

Examples:
* JAWS Any Recent/ChromeAny recent 
* JAWS 2023.2303.144 /Chrome Any Recent
* JAWS 2023.2303.144.400/Chrome 116.0.5845.188

Note that when specific versions are required, opening the test plan should require the user to confirm their versions match the requirements.

Option B: Consider restructuring the information on the test queue page to better align with how the CG has been working, e.g., a heading for each test plan and a table with columns for AT, Browser, assignees, status, and actions. The version information could be specified in the AT and Browser columns.

**Comment by howard-e** [comment]
Discussions outside this issue and also described at https://github.com/w3c/aria-at-app/issues/792#issuecomment-1971331518 note that specifying the browser version will not be required for the short term.

**Comment by mcking65** [comment]
Since encountering the conditions that led to w3c/aria-at#1047, and recalling comments that @jscholes  has made in the past about clearly defining "recent", I want to open discussion about changing "any recent" to "VX or Later".

In other words, when adding a run to the queue in draft or candidate review, the admin would be able to choose between specifying either a minimum version or a required version for an AT. Then in the test queue table, for each run, the AT and version cell in the table would say something like "JAWS 2024.2310.70.400 or Later" or "JAWS 2024.2310.70.400".

This would eliminate ambiguity about version requirements.

If we go this route, it would be the responsibility of the community group to maintain a list of what it considers to be the most appropriate minimum versions to use during draft review. It would be the responsibility of the admin to specify those minimums when adding a run to the queue.

One way of doing this that would enable consistency across test runs with minimal administrative effort would be to enhance the "Manage Assistive Technology Versions" feature on the data management page so that we can specify which version is the current "Minimum Required for Draft Review". When a new version of an AT is released and the admin is adding it to the system, that would also be the time that an admin may consider changing what the current minimum is for future draft review.

By having the system keep track of which version of an AT is the current required minimum version for review, it would simplify the process of adding a run to the test queue. Admins would not have to remember what the community group recommends as the currently required minimum. When adding a run to the queue, an admin would be able to choose one of two version requirements: option 1: "Minimum Required Version or Later" or option 2: a specific version.

I'd like to discuss this with @jscholes  and @IsaDC before we finalize #952. James and Isabel, I will have this on our agenda for Tuesday morning.

**Comment by mcking65** [comment]
I think we should consider going with design option B instead of option A for two reasons:
1. It is getting increasingly difficult to manage the test queue because the CG work is now primarily organized by test plan, not by AT/browser combination. During meetings, we have to look across multiple tables to get the information we need to make decisions, and we are having to do too much back and forth between data management and test queue.
2. I am hesitant to invest any more design and engineering resource in the current test queue page because it is already apparent that the current test queue organization is not aligned with the working mode and it is pretty obvious that organizing by test plan is more appropriate.

I'd like to discuss the following proposal for reorganizing the test queue with @jscholes and @IsaDC before we finalize #952. It doesn't seem like this proposal would be much of a lift because it is all the same data using all the same UI components; they are simply arranged differently.

#### Test Queue Option B Proposal

The test queue page would be a series of tables like it is now, but instead of having tables that contain data for all runs for a given AT/browser combination, each table would contain data for all the runs for a specific test plan version.

Each test plan version that has one or more runs in the test queue would have a collapsible section where:
1. The section heading is an H2 with the test plan name, version, and phase, e.g. "Toggle Button V24.03.12 in Draft Review"
2. The section heading is a toggle that expands/collapses the section like the H2 elements on a [Test Plan Versions page]().
3. The section content includes:
    1. A link to the test plan, e.g., [View V24.03.12 of the Toggle Button Test Plan]()
    2. A button that opens the report status dialog. This is exactly the same button that appears in the corresponding cell in the data management table.
    3. The test plan runs table described below. The table has an accessible name equal to the section heading, e.g., has aria-labelledby pointing to the H2.

The test plan runs table for a test plan version has the following columns:
1. AT: This will include the AT name and version requirement. Cells in this column are row headers, i.e., are `th` elements.
2. Browser: browser name and version requirement
3. Testers: contains the same content as the cells in the testers column of the current test queue tables.
4. Status: contains the same content as the cells in the status column of the current test queue tables with **one exception** noted below.
5. Actions: contains the same content as the cells in the actions column of the current test queue tables.

**Note about status column:** The current status includes strings like "Draft" or "Has Conflicts". Replace the that text portion of the status with the string "X% complete by Y testers with Z conflicts" where Percent complete = (NUMBER_COMPLETED_TESTS_BY_ALL_TESTERS / (NUMBER_ASSIGNED_TESTERS * NUMBER_TESTS_IN_PLAN)) * 100.

Here's an example.


<html>
<h2 aria-owns="sum1"></h2>
<details>
  <summary id="sum1">Toggle Button V24.03.12 in Draft Review</summary>
  <a href="https://aria-at.w3.org/test-review/74559">View V24.03.12 of Toggle Button Test Plan</a>
  <button>Required Reports in Progress</button>
  <table aria-labelledby="sum1">
    <thead>
      <tr>
        <th>AT</th>
        <th>Browser</th>
        <th>Testers</th>
        <th>Status
        <th>Actions</th>
      </tr>
      </th>
    </thead>
    <tbody>
      <tr>
        <th>JAWS 2023.2307.37 or Later</th>
        <td>Chrome (Any version)</td>
        <td>
          <button>Assign testers</button>
          <button>Assign Yourself</button>
          <ul>
            <li>IsaDC 2 of 8 tests complete</li>
            <li>hadirangin 2 of 8 tests complete</li>
          </ul>
        </td>
        <td>25% complete by 2 testers with 0 conflicts</td>
        <td>
          <button>Remove</button>
          <button>Run as other tester</button>
          <button>Delete for...</button>
        </td>
      </tr>
      <tr>
        <th>NVDA 2023.2 or Later</th>
        <td>Chrome (Any version)</td>
        <td>
          <button>Assign testers</button>
          <button>Assign Yourself</button>
          <ul>
            <li>IsaDC 2 of 8 tests complete</li>
            <li>mcking65 0 of 8 tests complete</li>
          </ul>
        </td>
        <td>13% complete by 2 testers with 0 conflicts</td>
        <td>
          <button>Remove</button>
          <button>Run as other tester</button>
          <button>Delete for...</button>
        </td>
      </tr>
      <tr>
        <th>VoiceOver 14.1.2 or Later</th>
        <td>Safari  (Any version)</td>
        <td>
          <button>Assign testers</button>
          <button>Assign Yourself</button>
          <ul>
            <li>IsaDC 2 of 8 tests complete</li>
            <li>jha11y 2 of 8 tests complete</li>
          </ul>
        </td>
        <td>25% complete by 2 testers with 0 conflicts</td>
        <td>
          <button>Remove</button>
          <button>Run as other tester</button>
          <button>Delete for...</button>
        </td>
      </tr>
    </tbody>

  </table>
</details>

</html>

**Comment by IsaDC** [comment]
@mcking65  Agree with these changes.

**Comment by isaacdurazo** [comment]
Here's a Mockup for Option B Proposal.

@mcking65 This mockup looks exactly like your html example. I only made one additon, which is a progress bar above "X% complete by Y testers with Z conflicts" in the status column. Cc @ccanash 

![ARIA-AT - Test Queue – 7](https://github.com/w3c/aria-at-app/assets/1379244/7fa19e35-8e2e-41aa-9212-65670108994b)
