### ISSUE TITLE
React bootstrap modal does not prevent focus from entering browser interface

### ISSUE THREAD

**Issue by stalgiag** [w3c/aria-at-app#805]
This issue was surfaced by #785 and #757. The current version of the React Bootstrap modal component does not prevent focus from entering the browser interface. Our dialog components extend the React Bootstrap modal component so our dialog components also have this behavior. This is expected behavior on React Bootstrap's side but it does not match the APG dialog example.

Browsers (tested on Chrome) prevent modification of focus during an event that would lead to focusing on browser interface elements. The to-do here is to follow the APG example and insert focusable divs before and after the ~~dialog~~ dialog content*. We can then use these barrier divs to detect focus events and wrap within the boundaries of the dialog.

*Edited for clarity. Thanks @jscholes !

**Comment by jscholes** [comment]
> insert focusable divs before and after the dialog

One note of nuance: they should be placed before and after the dialog content, but inside the container with `role="dialog"`.  Moving focus outside the dialog onto such a `div`, and then back in, would cause overly verbose screen reader behaviour.
