### ISSUE TITLE
Define required AT versions for reporting on recommended test plans

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-at-app#809]
#### Goal for updating reports on recommended test plans

One goal of the ARIA-AT working mode specific to test plans in the recommended phase is to keep their interop reports current. That means, for each AT/Browser combo that has a report, generate a new report when a new version of an AT or browser is released. In addition to keeping data current, over time, this will also create data that can be used to publish trend charts.

As of September 27, 2023, the CG plans to update recommended reports for each public release of a supported screen reader; see [Minutes for ARIA and Assistive Technologies Community Group Weekly Teleconference – 27 September 2023](https://www.w3.org/2023/09/27-aria-at-minutes.html#t04). Until the ARIA-AT project has sufficient automation and compute resources, new browser releases will not trigger report updates. The browser requirement will be "Any Recent Version". In the event of report run conflicts that are attributable to browser version differences, data from the more recent browser version will be published.

#### Problem - Determining which AT versions require reports

Once a test plan becomes recommended, for which AT versions should reports be required?

Some options:
* Option A: the earliest version used to generate any of the approved published reports for that plan
Option B: * The latest version used to generate any of the approved published reports for that plan
* Option C: Any versions released after the plan becomes recommended

Note: The reports that are published as approved may have been generated during draft review. It is possible that several new AT versions were released between the time that a plan completed draft review and the time the plan finished candidate review and became recommended.

**Comment by ccanash** [comment]
Closing as we implemented option B as part of the test queue updates and include in PR #1123
