### ISSUE TITLE
Change button label from "Unassign yourself" to "Delete your test plan run"

### ISSUE THREAD

**Issue by jugglinmike** [w3c/aria-at-app#830]
From @mcking65 in [gh-732](https://github.com/w3c/aria-at-app/issues/732#issuecomment-1781882610):

> I didn't realize a tester could "delete" their work by "unassigning" themselves. I should test that out. The function should be named "delete", not "unassign".

**Comment by ccanash** [comment]
Hi @mcking65 , what should be the priority of this task?
