### ISSUE TITLE
The version string elements are empty when test plan version is advanced on Data Management Page

### ISSUE THREAD

**Issue by ccanash** [w3c/aria-at-app#836]
After advancing a test plan version on the Data Management page, the text included for the version string elements in the cells of that row is empty. A refresh solves it which indicates a data persistence problem with the version string values.

Resolving this should also solve a related comment in https://github.com/w3c/aria-at-app/issues/785#issuecomment-1749887927:

> After saving a new target date value, the link for the test plan version is getting corrupted. The text of the link goes away. In particular, this element inside of the link, `<b>V22.03.17</b>`, is empty after saving a new target date value.

**Comment by mcking65** [comment]
Verified fix.
