### ISSUE TITLE
Report status dialog does not show all valid AT/browser combinations for draft and candidate test plans and add to queue button is missing for reports that are not required

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-at-app#873]
After advancing a plan from R&D complete to Draft review, the report status dialog only shows status for required reports. Reports that are not required should also be listed.

![image](https://github.com/w3c/aria-at-app/assets/7241781/2439bf61-1be1-4f8b-bdaf-86d3330d775e)

If you use the add to queue disclosure at the top of the test queue page to add a test run to the test queue for a AT/browser combination that is not required during the draft review phase, the report status dialog will show the correct status. For example, NVDA with Firefox is not required during draft review, and the report status dialog will show status for that report if it has been added to the queue. However, the report status dialog is still missing rows for other reports that are not required, e.g., JAWS and Firefox, VoiceOver with Chrome.

![image](https://github.com/w3c/aria-at-app/assets/7241781/428118ec-93b8-427a-9a53-e15214432bcc)

When a test plan advances to draft review, the report status dialog should show lines for all valid AT/browser combinations, including those that are not required. There should be an "Add to Queue" button for every combination.

**Comment by Paul-Clue** [comment]
> If you add a test run to the test queue for a draft test plan for a AT/browser that is not required during the draft review phase, the add to test queue button is missing from the report status dialog. For example, add a run for NVDA and Firefox to the queue for a draft test plan. Then open the report status dialog for that version of the test plan. The correct status is shown for NVDA and Firefox, but the add to test queue button is not present. It should be there.

Right now the application works in a way such that it is one AT/Browser combination for any given test plan version. This comment implies that multiple combinations could exist for a test plan version.
Is this related to #870? This may explain why it can't be done just yet: https://github.com/w3c/aria-at-app/issues/870#issuecomment-1864944498

**Comment by mcking65** [comment]
> > If you add a test run to the test queue for a draft test plan for a AT/browser that is not required during the draft review phase, the add to test queue button is missing from the report status dialog. For example, add a run for NVDA and Firefox to the queue for a draft test plan. Then open the report status dialog for that version of the test plan. The correct status is shown for NVDA and Firefox, but the add to test queue button is not present. It should be there.
> 
> @mcking65, right now the application works in a way such that it is one AT/Browser combination for any given test plan version. This comment implies that multiple combinations could exist for a test plan version. Is this related to #870? This may explain why it can't be done just yet: [#870 (comment)](https://github.com/w3c/aria-at-app/issues/870#issuecomment-1864944498)
> 
> cc @lolaodelola


@Paul-Clue 

So sorry, my issue title and description are not consistent with one another. The title is correct, and the first paragraph of the description is correct. The paragraph you quoted is incorrect and misleading.

Here is what it should say. I have corrected the original.

>If you add a test run to the test queue for a draft test plan for a AT/browser that is not required during the draft review phase, the report status dialog will show the correct status. However, the dialog is still missing rows for other reports that are not required.
>
>When a test plan advances to draft review, the report status dialog should show lines for all valid AT/browser combinations, including those that are not required. There should be an "Add to Queue" button for every combination.
