### ISSUE TITLE
Deprecated test plans remain in test queue and in-progress results are lost when a newer test plan version deprecates an older test plan version

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-at-app#877]
Advancing a new version of a test plan to draft review caused the test queue to contain test runs for a deprecated test plan version and cause the loss of previously completed work on manual test runs.

The procedure that manifest this bug was:
1. Command button V23.12.06 was in draft review and had three test runs in the test queue.
2. Results were present for all the runs.
3. We discovered that a change was needed to the settings specified for two VoiceOver commands.
4. We made V23.12.13 of the plan with the changes to the VoiceOver commands and merged it to master so it showed on the data management page as R&D Complete.
5.  We advanced V23.12.13 of the command button test plan to draft review.

Expected results:
1. Since V23.12.06 is deprecated, its runs no longer show in the test queue.
2. To avoid unnecessary loss of manual test work, equivalent runs of V23.12.13 are added to the test queue, preserving as many test results as possible.

Actual results:
1. Runs of V23.12.06, which became deprecated,  remain in the test queue.
2. Runs of V23.12.13 that we subsequently added to the test queue were empty, so testers have to start over even for tests that were not changed.

### Requirements for data preservation during test plan deprecation

To prevent unnecessary loss or repetition of manual test run work, the system needs to determine which test results can be preserved when a version of a test plan is deprecated as the result of a test plan advancing into draft review, into candidate review, or into recommended.

the system should:
1. Identify AT/browser preservation candidates: For each AT/browser combination supported by the test plan, identify the AT/browser combinations for which the deprecated plan has results (either draft or final) and the new plan version does not have results. If the new version has results for a given combination, it is not necessary to attempt to copy any results from the prior test plan version to the new test plan version for that AT/browser combination. This comparison can ignore AT and browser versions, e.g., if the new plan version and the deprecated plan version both have results for JAWS/Chrome, the version of JAWS and Chrome are un important. There is no need to copy results for JAWS/Chrome in that scenario.
2. Identify preservable results: For each AT/browser preservation candidate, identify the test/assertion/command/settings that are equivalent in the new and deprecated plans.
3. If an AT/Browser preservation candidate has a final report generated from the deprecated test plan and if all results are preservable, copy the final report from the deprecated test plan to the new test plan.
4. If an AT/Browser preservation candidate has a final report generated from the deprecated test plan and if some but not all results are preservable, then:
    1. copy results for the equivalent tests/assertions/commands into new incomplete test plan runs.
    2. Add the incomplete runs to the test queue; assign to the same testers who previously generated the results.
5. If an AT/Browser preservation candidate has a run in the test queue and any of its results are preservable, then:
    1. copy results for the equivalent tests/assertions/commands into new incomplete test plan runs.
    2. Add the incomplete runs to the test queue; assign to the same testers who previously generated the results.
    3. Remove the test plan runs for the deprecated test plan version from the test queue.

**Comment by lolaodelola** [comment]
@mcking65 This is currently being worked on and I know you wanted to add more information here, please let us know if there's any more info or context you want to include.

**Comment by mcking65** [comment]
@lolaodelola @howard-e 

I finally got the requirements clearly specified in the top comment. Please use those requirements for testing resolution of this bug.

**Comment by mcking65** [comment]
Tested by advancing link test plan v23.12.13 from draft to candidate. The prior version (v23.12.06) had multiple runs in the test queue and some runs complete. The advancement of the new version went perfectly.

Caveat: I didn't look at all the assertions in the test plan before and after advancing the new version to make 100% sure all equivalent results were kept and 0 verdicts that were associated with changed assertions were not kept. I am counting on the eng team to have tests in place that cover results migration. I primarily focused on the state of the queue and random checking of test plan results migration.
