### ISSUE TITLE
Add trend reports project brief to GH

### ISSUE THREAD

**Issue by ccanash** [w3c/aria-at-app#906]

**Comment by mcking65** [comment]
First draft of [project readme](https://github.com/orgs/w3c/projects/67/views/1?pane=info) is ready for review.

@ccanash, would you please add a project column for primary deliverable and add the 4 primary deliverables I listed in the project readme as values. Then, each issue in the project can be associated with one of those deliverables and we can slice on deliverable. I believe the 2 P1 deliverables will have the most issues.

BTW, I put a priority on the deliverable. That does not mean all the issues associated with a deliverable will have that priority. It is just an indicator of what I think overall sequencing should be. If that is not helpful or confusing, we could remove the priority from the primary deliverables in the readme; I don't intend the primary deliverable priority to be reflected anywhere else.

**Comment by mcking65** [comment]
Closing as complete
