### ISSUE TITLE
Modify command results table to render the phrase form of the assertion specified in the assertionPhrase column of assertions.csv.

### ISSUE THREAD

**Issue by ccanash** [w3c/aria-at-app#949]
From comment in #744 

**Command results table content changes**
Update the table caption to match heading content.

In the assertion column, render the phrase form of the assertion specified in the assertionPhrase column of assertions.csv.

The table still shows the statement form of the assertion instead of the phrase form of the assertion. The phrase form is intended to make the table content easier to understand when reading across a row. For example, instead of:

Priority| Assertion | Result
--- | --- | ---
Must | Name 'W3C website' is conveyed | Passed

The table should read:

Priority| Assertion | Result
--- | --- | ---
Must | Convey name 'W3C website' | Passed

**Comment by Solidsilver7373** [comment]
> From comment in #744 
> 
> 
> 
> **Command results table content changes**
> 
> Update the table caption to match heading content.
> 
> 
> 
> In the assertion column, render the phrase form of the assertion specified in the assertionPhrase column of assertions.csv.
> 
> 
> 
> The table still shows the statement form of the assertion instead of the phrase form of the assertion. The phrase form is intended to make the table content easier to understand when reading across a row. For example, instead of:
> 
> 
> 
> Priority| Assertion | Result
> 
> --- | --- | ---
> 
> Must | Name 'W3C website' is conveyed | Passed
> 
> 
> 
> The table should read:
> 
> 
> 
> Priority| Assertion | Result
> 
> --- | --- | ---
> 
> Must | Convey name 'W3C website' | Passed
> 
> 
> 
> 
> 
> 

Close
