### ISSUE TITLE
Version histories are showing incorrect deprecation dates

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-at-app#966]
The last deployment of the app broke an important working mode requirement.

The deprecation date of a test plan that was deprecated during candidate review should be the same date that the newer version was advanced to candidate. There are several test plans where the deprecation date of plans deprecated during candidate review are incorrect.

I remember spending a lot of time checking this functionality for nearly all test plans last summer, and I believe we resolved all inconsistencies. Now it appears there are regressions in the functionality and data has changed in unexpected ways.

For example, look at the alert example on the candidate review page. It shows that the candidate review start date is Jan 11, 2024.

![image](https://github.com/w3c/aria-at-app/assets/7241781/82e2dcde-543e-44ba-bd9c-a44b84243041)

However, you can see from the [timeline for all versions of the alert test plan](https://aria-at.w3.org/data-management/alert) that candidate review of the alert test plan started on Dec 9, 2022 when V22.12.08 advanced to candidate.

![image](https://github.com/w3c/aria-at-app/assets/7241781/f2a2aad6-4c58-4a56-a18c-d969164b1a3c)

While the alert plan has the correct deprecation date for v22.12.08 when V23.12.06 was advanced to candidate review, there are other test plans where the deprecation date is inconsistent with other dates in the timeline. For example, look at the [Disclosure Navigation Menu Example Test Plan](https://aria-at.w3.org/data-management/disclosure-navigation).
For this test plan, the timeline shows that Candidate Review Started on Dec 1, 2021 when V21.11.30 advanced to candidate. The timeline also shows that V21.11.30 was deprecated on Dec 1, 2021. Look further down the timeline and you can see that the next version to advance to candidate was V22.10.31 on Nov 1, 2022. So, that should be the deprecation date for V21.11.30. In addition, the candidate review and data management pages show that candidate review started on Nov 1, 2022 but the versions timeline shows that candidate review started Dec 1, 2021. I question that Dec 1, 2021 date, though; I don't remember when we first advanced a plan to candidate, but that seems earlier than I recall. At any rate, the timeline is inconsistent.

![screenshot of disclosure test plan timeline](https://github.com/w3c/aria-at-app/assets/7241781/a840c070-6660-4a2f-b7a2-f8dc94fdad51)

Similarly, in the [Radio Group Example Using aria-activedescendant Test Plan](https://aria-at.w3.org/data-management/radiogroup-aria-activedescendant), the deprecation date for the version that was deprecated when V23.04.10 advanced to candidate is incorrect. V23.04.10 advanced to candidate on Apr 11, 2023. When it advanced, it deprecated V22.05.18. However, the deprecation date shown for V22.05.18 is Dec 8, 2022, but it should be Apr 11, 2023. The data management and candidate review pages show that candidate review started on Apr 11, 2023, but it actually started on May 19, 2022.

**Comment by howard-e** [comment]
> When a test plan advances to candidate, if there is an earlier version of that plan in candidate review, the candidate review start and target completion dates should not be changed. Now, the candidate review start dates are incorrect for all test plans in candidate review. In addition, target dates were changed for all test plans advanced after the latest release of the app, so they are also incorrect. We can no longer see how overdue those plans are.

As agreed in another discussion, the above is a one issue and the rest of the top comment is another

**Comment by ccanash** [comment]
Hi @mcking65  created task #973  with the first part of your comment, updated the title of this issue and also modified the task description.
