### ISSUE TITLE
Enhanced conflict review

### ISSUE THREAD

**Issue by ccanash** [w3c/aria-at-app#975]
Support reviewing conflicts with Test Plan Runs for Test Plan Reports in the "Candidate" and "Recommended" phases

**Problem**

When conflicts are being evaluated it is done while the relevant AT + Browser combination for a Test Plan Version has not yet been marked as final (so still present on the Test Queue page). When there, it would allow testers and authors to go over the conflicts that testers have when recording results between their Test Runs.

Eventually, those conflicts are resolved between the testers’ runs and the reports are pushed forward to the CANDIDATE / RECOMMENDED phases. Eventually new reports may be created for the same combination of Test Plan Version + AT + Browser, but with different Browser / AT Version values and added to the Test Queue. But it would then mean the previous reports’ results are unable to be compared against the newly created report and that may be a desirable condition to have.

**Comment by boazsender** [comment]
@ccanash and @mcking65 How about we update the test-que with these changes to support this:

## Add deep linking to each test in the test plan

## Create a new test-conflicts ui at /test-que/:test-plan-report-id/conflicts

1. List of all tests in test-plan that have conflicts
2. Click on each test plan to open a disclosure that summarizes the conflicts and provides action buttons: a) Raise an issue, b) Admins: edit test-plan-report (brings the admin to the existing test plan run page)

## When a test-plan-report has conflict(s)

1. Add label to the test-plan-report that indicates who the conflict is between. 
2. Add a link to the test conflicts page

## For all test-plan-reports

1. Add a link from the test-plan-report to the test-plan-report version history for that test plan in the data management section

## When a test-plan-report surfaces a conflict for an already recommend report, add it to the test que, and show that it has conflicts
