### ISSUE TITLE
Implement functionality for "View Log" button on Test Plan Run page for automated bot runs

### ISSUE THREAD

**Issue by jugglinmike** [w3c/aria-at-app#989]
On Test Plan Runs assigned to "bot" users, the "Test Options" menu includes a button labeled "View Log". As of this writing, that button has no associated functionality, but it was designed to serve as a link to an externally-hosted text file which describes the progress of the automated AT response collection process. (Today, that host is the GitHub Actions service.) Implement that functionality.

**Comment by alflennik** [comment]
@gnarf I didn't notice it when I reviewed the PR, but instead of writing "Fixes #989" in the PR description (which will close the issue when that PR is merged), you should write "See #989". It's an interesting GitHub feature. Probably useful in some projects. But not so much this one.

**Comment by mcking65** [comment]
Moved to automation project; I don't consider this maintenance.
