### ISSUE TITLE
Update the Assign Tester Menu to support type-ahead

### ISSUE THREAD

**Issue by howard-e** [w3c/aria-at-app#991]
During a [recent CG meeting](https://www.w3.org/2024/03/27-aria-at-minutes.html#t04), it came up that with more testers now being added into the system, it is getting increasingly difficult for an admin to find the tester they'd like to assign from the list of options.

A suggestion is to make the menu support type-ahead to make it easier for an admin to assign a tester, given that they already know the username of the tester to be assigned. ie. pressing M to jump to testers beginning with M.

**Comment by jscholes** [comment]
@howard-e I don't think @mcking65 was asking for a combobox with autocomplete/search.  Rather, just that the menu support type-ahead, i.e. you can press M to jump to testers beginning with M, as per the [APG example](https://www.w3.org/WAI/ARIA/apg/patterns/menu-button/examples/menu-button-actions-active-descendant/).  Multi-select comboboxes are hard to implement and often hard to use.

**Comment by howard-e** [comment]
@jscholes thanks for clarifying! I can update the top comment to reflect
